### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by amitxv** [amitxv/StresKit#2]
- [ ] document changing mitgations by mounting to a usb with rufus
- [x] parse args with argparse
- [x] either instructions to use vi in README or simple frontend for linpack and get rid of lininput
- [x] default to "UNKNOWN" version if version is not specified for build script
- [x] add manual build instructions to README

**Comment by seansweda** [comment]
I think this project is a great idea.  I'm in the process of doing burn-in testing and can give this a try if you're looking for feedback.

**Comment by amitxv** [comment]
Hi, feedback is much appreciated. Thanks

**Comment by seansweda** [comment]
OK great, should I continue to add comments to this issue or do you prefer I open a new one?

**Comment by seansweda** [comment]
first suggestion would be to add [S-TUI](https://github.com/amanusk/s-tui) as an improvement to watch sensors

**Comment by amitxv** [comment]
Added s-tui in v1.4.0. I will look into integrating FIRESTARTER too. As for issue reporting, I don't mind where feedback is given 👍

**Comment by amitxv** [comment]
Instructions to toggle mitigations added in https://github.com/amitxv/StresKit/commit/37aaef61cb8de7711621ae01c0a47b44add9537b.
